hv_consep:
  step_size: [80, 80]
  win_size: [270, 270]
  nuclei_types:
    # Background: 0
    Misc: 1
    Inflammatory: 2
    Epithelial: 3
    Spindle: 4

hv_pannuke:
  step_size: [164, 164]
  win_size: [256, 256]
  nuclei_types: # check GT if used with original model
    # Background: 0
    Inflammatory: 1
    Connective: 2
    Dead cells: 3
    Epithelial: 4
    Neoplastic cells: 5